version: "3.7"
services:
  server:
    build: ./server
    container_name: server
    restart: always
    environment:
      - DB_HOST=mongodb
      - DB=rate-limiter
      - REDIS_URI=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/app
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      mongodb_INITDB_DATABASE: rate-limiter
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6:/scripts
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:8.5.21
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
volumes:
  data-volume:
  cache:
networks:
  k6:
  grafana:
